dynamic_schemas/urls.py
from django.conf.urls import url

from . import views


app_name = 'dynamic_schemas'
urlpatterns = [
    url(r'^$', views.SchemaIndexView.as_view(), name='schema_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.SchemaView.as_view(), name='schema_view'),
    # url(r'^(?P<pk>[0-9]+)/$', views.SchemaView, name='schema_detail'),
    url(r'^(?P<pk>[0-9]+)/create/$', views.form_view, name='create_form'),
    # url(r'^(?P<pk>[0-9]+)/(?P<r_pk>[0-9]+)/update/$',
        # views.ResponseUpdate.as_view(), name='update_response'),
    url(r'^(?P<pk>[0-9]+)/(?P<r_pk>[0-9]+)/update/$',
        views.form_update_view, name='update_response'),
    url(r'^(?P<pk>[0-9]+)/responses/$', views.ResponseList.as_view(),
        name='list_responses'),
    url(r'^(?P<pk>[0-9]+)/columns/$', views.ResponseColumns.as_view(),
        name='response_columns'),
]

dynamic_schemas/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from .models import Schema, SchemaColumn, SchemaResponse, SchemaUrl


# Rename ResponseForm
SELECT_CHOICES_EDIT = [ 
    ('------', '------'),
    ('Nej','Nej'), 
    ('Ja','Ja'), 
    ]
SELECT_CHOICES = [
    ('Nej', 'Nej'),
    ('Ja', 'Ja'),
    ]
SELECT_LEN = len(SELECT_CHOICES)


class SchemaResponseForm(forms.Form):

    def __init__(self, schema, *args, **kwargs):

        super().__init__(*args, **kwargs)
        
        self.schema = schema
        self.schema_columns = schema.schemacolumn_set.all()
        
        self.URLS = self.schema.help_field.values_list('id', 'name')
        # import ipdb; ipdb.set_trace()
        # self.schema_urls = schema.schemaurl_set.all()
        # import ipdb; ipdb.set_trace()
        for column in self.schema_columns:
            if column.is_bool and column.is_editable_once:
                self.fields[column.text] = forms.ChoiceField(
                    choices=SELECT_CHOICES_EDIT,
                    widget=forms.Select(
                        attrs={'class': 'form-control'}
                        )
                    )
            elif column.is_bool and not column.is_editable_once:
                self.fields[column.text] = forms.ChoiceField(
                    choices=SELECT_CHOICES,
                    widget=forms.Select(
                        attrs={'class': 'form-control'}
                        )
                    )
            else:
                self.fields[column.text] = forms.CharField(
                    max_length=200,
                    required=False,
                    empty_value='',
                    widget=forms.TextInput(
                        attrs={'class':'form-control'}
                        ),
                    )

        self.fields['instruktion'] = forms.ChoiceField(
              choices=self.URLS,
              widget=forms.Select(
                  attrs={'class': 'form-control'}
                  )
              )

    def save(self, commit=True, *args, **kwargs):

        if self.cleaned_data:
            instr_id = self.cleaned_data.pop('instruktion')
            instr_inst = get_object_or_404(SchemaUrl, pk=instr_id)

            instance = SchemaResponse(
                schema=self.schema,
                qa_set=self.cleaned_data,
                instruction=instr_inst,
                )

            if commit:
                instance.save()

        return instance


class ResponseUpdateForm(forms.Form):

    """
    Handles the form for updating the fields.
    """
    
    def __init__(self, instance, pk, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.instance = instance 
        self.schema = Schema.objects.get(pk=pk)
        self.schema_columns = self.schema.schemacolumn_set.all()
        self.c_widget = forms.Select(
            attrs={'class': 'form-control'},
            )
    
        for column, answer in instance.qa_set.items():
            queried_column = SchemaColumn.objects.get(schema=self.schema,
                                                   text=column)

            # If is_bool, we don't want it to be editable untill
            # proper conditions have been setup for such a scenario.
            if queried_column.is_bool:
                if queried_column.is_editable_once \
                and answer == SELECT_CHOICES_EDIT[0][0]:
                    # SELECT_CHOICES_EDIT[0][0] first tuple, first value
                    self.fields[column] = forms.ChoiceField(
                        choices=SELECT_CHOICES_EDIT,
                        widget=self.c_widget
                        )
                    self.fields[column].widget.attrs['disabled'] = False

                else:
                    self.fields[column] = forms.CharField(
                        initial=answer, 
                        widget=forms.TextInput(
                            attrs={'class': 'form-control', 'disabled': True}
                            )
                        )

            elif not queried_column.is_editable_once or answer != '':
                self.fields[column] = forms.CharField(
                    required=False,
                    max_length=100,
                    initial=answer,
                    widget=forms.TextInput(
                        attrs={'class':'form-control', 'disabled': True}
                        )
                    )
                
            else:
                self.fields[column] = forms.CharField(
                    required=False,
                    max_length=100,
                    initial=answer, # Should be empty '' else remove this field
                    widget=forms.TextInput(
                        attrs={'class': 'form-control'}
                        )
                    )

    def is_valid(self):
        # Parent validation first, get cleaned data.
        """ Cleans own data, makes sure columns is editable and is empty """
        editable_columns = { 
            c.text:
            c.is_editable_once for c in self.schema_columns
            } 
        exists = {} 
        for key, value in self.data.items():
            if key in self.instance.qa_set \
            and editable_columns[key] \
            and (self.instance.qa_set[key] == '' \
            or self.instance.qa_set[key] == '------'):
                exists[key] = value

        if exists:
            self.cleaned_data = exists
            return True

        return False


    def update(self, *args, **kwargs):
        if self.cleaned_data:

            # __import__('ipdb').set_trace()
            for key, value in self.cleaned_data.items():
                self.instance.qa_set[key] = value
            self.instance.save()

        else:
            return ValidationError("NOT VALID")

dynamic_schemas/views.py
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer

from .models import Schema, SchemaColumn, SchemaResponse, SchemaUrl
from .forms import SchemaResponseForm, ResponseUpdateForm
from .serializers import SchemaResponseSerializer
from .prepare_data import getcolumns

import pytz

class SchemaIndexView(LoginRequiredMixin, ListView):
    # login_url = '/accounts/login.html/'
    template_name = 'dynamic_schemas/index.html'
    context_object_name = 'all_schemas'

    def get_queryset(self):
        return Schema.objects.all()


@login_required
def form_view(request, pk):
    schema = Schema.objects.get(pk=pk)
    urls = schema.help_field.all()

    if request.method == 'POST':
        form = SchemaResponseForm(schema, request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            
        return redirect(reverse('dynamic_schemas:schema_view',
                                kwargs={'pk': pk}))
    else:
        form = SchemaResponseForm(schema)

    return render(request, f'dynamic_schemas/create-form.html', \
        {
        'form': form,
        'schema': schema,
        'help_urls': urls,
        })


@login_required
def form_update_view(request, pk, r_pk):
    schema = Schema.objects.get(pk=pk)
    instance = SchemaResponse.objects.get(schema=schema, pk=r_pk)

    columns = SchemaColumn.objects.filter(schema=schema)

    ###################################################
    # This little snippet checks if the responses can be edited. If they can
    # the submit button will be provided. There is no restriction on
    # has_been_edited, but since the data cant be saved we're good for now.
    load_button = False
    aggr_editables = [c.is_editable_once for c in columns]

    if True in aggr_editables:
        load_button = True
    ###################################################

    form = ResponseUpdateForm(instance, pk)

    if request.method == 'POST':
        form = ResponseUpdateForm(instance, pk, request.POST or None)
        if form.is_valid():
            form.update()
        return redirect(reverse('dynamic_schemas:schema_view',
                                        kwargs={'pk': pk}))
        
    return render(request, f'dynamic_schemas/update-form.html', 
            {'form_update': form,
            'load_button': load_button}
            )


""" API Views """

class MakeDataPrettyMixin:
    def _make_date_tz(self, instance=None, tz=None):
        """ Takes an instance, and sets its timezone. 
        
            TODO: 
            Should this be a classmethod? Will a classmethod complicate the
            view in its context?

        """
        # Can this be moved to SETTINGS instead? Same for _make_date_readable.
        # Problem is probably that the UTC format gets overridden.
        if instance:
            if tz:
                tz = pytz.timezone(tz)
            return instance.pub_date.astimezone(tz)
        return

    def _make_date_readable(self, instances):
        """ 
        Helper function to change the dates to a format pleasing to the
        eyes, takes a bundle of instances and converts their time.
        How extensible do we want this?
        Function is kept private for now, since in Denmark the timezone is CET.
        """
		
        for instance in instances:
            inst_as_cet = self._make_date_tz(
                    instance=instance
                    # tz='Europe/Copenhagen'
                    )
            instance.pub_date = inst_as_cet \
                    .strftime('%d-%m/%Y %H:%M:%S')

        return instances

    def _make_user_readable(self, serializer):
        """ Helper to return the correct attributes to the front-end
        """
        for data in serializer.data:
            # import ipdb; ipdb.set_trace()
            user = data['user']
            instance = User.objects.get(id=user)

            user = instance.first_name + instance.last_name

            if instance.first_name == '':
                user = instance.username

            data['user'] = user
            # __import__('ipdb').set_trace()
            # import ipdb; ipdb.set_trace()

        return serializer 

    def _make_intruction_links_readable(self, serializer):
        for data in serializer.data:
            instr = data['instruction']
            instance = SchemaUrl.objects.get(id=instr)
            
            instr = '<a href="'+ instance.url +'">'+ instance.name +'</a>'

            data['instruction'] = instr

        return serializer

class ResponseList(MakeDataPrettyMixin, APIView):

    """
    Lists responses according to schema.
    Purely for APIView for now. Not being used in the actual rendering af the
    tables.
    """
    default_order = [
        ('desc', '-'),
        ('asc', ''),
        ]

    def get_orderprefix(self, order):
        for tup in self.default_order:
            if order in tup:
                return tup[1]
    
    def get(self, request, pk, format=None, *args):
        req = request.GET
        # Amount of data to fetch each pull
        start = int(req.get('start', 0))
        length = int(req.get('length', 30))
        end = start + length;

        order = req.get('order[0][dir]')
        order_column = req.get('order[0][column]')
        order_by_pre = self.get_orderprefix(order)
        order_column_name = req.get('columns['+order_column+'][data]')
        # __import__('ipdb').set_trace()
        order_str = order_by_pre + order_column_name

        draw = req.get('draw')

        # TODO Gonna require some thinking. Also need to user recordsFiltered.
        # search = req.get('search[value]')

        schema = Schema.objects.get(pk=pk)
        responses_count = SchemaResponse.objects.filter(schema=schema).count()
        responses = SchemaResponse \
            .objects \
            .filter(schema=schema) \
            .order_by(order_str)[start:end]
        # __import__('ipdb').set_trace()
        responses = self._make_date_readable(responses)

        serializer = SchemaResponseSerializer(responses, many=True)
        serializer = self._make_user_readable(serializer)
        serializer = self._make_intruction_links_readable(serializer)

        return_data = {
            'draw': int(draw),
            'recordsTotal': responses_count,
            'recordsFiltered': responses_count,
            'data': serializer.data,
            }
        # __import__('ipdb').set_trace()
        return Response(return_data)

class ResponseColumns(APIView):
    def get(self, request, pk, format=None, *args):
        req = request.GET
        schema = Schema.objects.get(pk=pk)
        sr = SchemaResponse.objects.filter(schema=schema).first()
        columns = getcolumns(sr).getvalue()

        return Response(columns)



class SchemaView(LoginRequiredMixin, APIView):

    """
    Fetches the FIRST object from ResponseList. Makes it availabe for
    as a template for the table in main.html

    Excludes schema.id, and the placeholder qa_set in the template.

    """

    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'dynamic_schemas/table_dev.html'


    def get_object(self, pk):
        try:
            schema = Schema.objects.get(pk=pk)

            if SchemaColumn.objects.filter(schema=schema).count() != 0:
                all_responses = SchemaResponse.objects.filter(schema=schema) 
                single_response = all_responses.first()
                serializer = SchemaResponseSerializer(single_response)
                return serializer.data

        except single_response.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        schema = Schema.objects.get(pk=pk)
        schema_help_urls = schema.help_field.all()
        schema_obsolete = schema.obsolete.all()
        schema_new = schema.new.all()
        

        all_responses = SchemaResponse.objects.filter(schema=schema) 
        # self._make_date_readable(all_responses)

        serializer = SchemaResponseSerializer(all_responses, many=True)

        data = {'single_response': self.get_object(pk),
                'all_responses': serializer.data,
                'pk': pk,
                'schema': schema,
                'help_urls': schema_help_urls,
                'schema_obsolete': schema_obsolete,
                'schema_new': schema_new,
                }

        # __import__('ipdb').set_trace()
        return Response(data)

dynamic_schemas/templates/dynamic_schemas/base.html
{% load static %}
<html>
    <head>
        <title>Rengøring</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="icon" 
              href="{% static 'dynamic_schemas/icons/ren_ico.png' %}" />
        <link rel="stylesheet"
              href="{% static 'dynamic_schemas/css/style.css' %}" />
        <!--<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />-->
        <link rel="stylesheet" type="text/css" href="{% static 'dynamic_schemas/dependencies/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />

        <!--<script-->
          <!--src="https://code.jquery.com/jquery-3.2.1.min.js"-->
          <!--integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="-->
          <!--crossorigin="anonymous"></script>-->
          <script type="text/javascript" src="{% static 'dynamic_schemas/dependencies/jQuery/jquery-3.2.1.min.js' %}"></script>
        <!--<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
        <script type="text/javascript" src="{% static 'dynamic_schemas/dependencies/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
        {% block extraheads %}
        {% endblock %}
    </head>

    <body>
        {% if request.user.is_authenticated %}
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" 
                       href="{% url 'dynamic_schemas:schema_list' %}">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        Damino Systems 
                    </a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li id='admin-help'>
                        <a href="http://www.github.com/Threemusketeerz/DSystems/blob/master/dynamic_schemas/docs/admin_readme.md">
                            <span class='glyphicon glyphicon-info-sign'></span>
                            Admin guide
                        </a>
                    </li>
                    <li class="depr-schema">
                        <a href="http://10.22.1.15/hjemmeside/hjemmeside.html"> Udgået skema system </a>
                    </li>
                    {% if schema %}
                    {% block navextras %}
                    {% endblock %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"
                                                   aria-expanded="true">
                            Instruktioner
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% if help_urls %}
                                {% for link in help_urls %}
                                <li><a href="{{ link.url }}" 
                                       target="_blank" 
                                       id="btn{{ forloop.counter }}">
                                        {{ link.name}}
                                    </a>
                                </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}
                    <li>
                        <a {% if request.user.is_superuser %}href="{% url 'admin:index' %}"{% endif %}>
                            <span class="glyphicon glyphicon-user"> </span>
                            {{ request.user.username }}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-log-out"></span>
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        {% endif %}

        {% block above_content %}{% endblock %}
        <div class="content-container">
            {% block content %}
            {% endblock %}
        </div>
        {% block below_content %}{% endblock %}
    </body>
</html>

dynamic_schemas/templates/dynamic_schemas/create-form.html
{% extends 'dynamic_schemas/base.html' %}
{% load dynamic_schema_extras %}

{% block content %}
    <div class="form-container">
        <form class="form-box" action="" method="POST" >
            {% csrf_token %}
            {% if form %}
            {% for field in form %} 
            {% if field.is_hidden %} 
            {{ field }}
            {% elif field|is_a_checkbox %}
            <div class="form-check">
                <label class="form-check-label" for="id_{{ field.label }}"> 
                    {{ field }}
                    {{ field.label }}
                </label>
            </div>
            {% else %}
            {{ field.label_tag }}
            {{ field }}
            {% endif %}
            {% endfor %}
            {% endif %}
            <input type="submit" class="btn btn-default pull-right submit-btn" value="GEM"/>
        </form>
    </div>
{% endblock %}

dynamic_schemas/templates/dynamic_schemas/index.html
{% extends 'dynamic_schemas/base.html' %}
{% block content %}
    <div class="container">
        <div class="schema-menu">
            {% if all_schemas %}
            <div class="custom-btn-group">
                <h2> Rengørings skemaer </h2>
                <p class="help-text">Tryk på det ønskede skema, og oppe i toppen vil du finde en
                knap til dine behov! </p>
                {% for schema in all_schemas %}
                    {% if schema.is_active %}
                    <a href="{% url 'dynamic_schemas:schema_view' schema.id %}">
                        <button id="menu-btn" class="btn btn-default">{{schema.name}}</button>
                    </a>
                    {% endif %}
                {% endfor %}
            </div>
            {% else %}
                <h1> NO SCHEMAS </h1>
            {% endif %}
        </div>            
    </div>
{% endblock %}

dynamic_schemas/templates/dynamic_schemas/main.html
{% extends 'dynamic_schemas/base.html' %}
{% load static %}
{% load dynamic_schema_extras %}
{% block extraheads %}
        <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/b-1.5.0/r-2.2.1/sl-1.2.4/datatables.min.css"/>-->
        <link rel="stylesheet" type="text/css" href="{% static 'dynamic_schemas/dependencies/dt/datatables.min.css' %}">

        <!--<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/b-1.5.0/r-2.2.1/sl-1.2.4/datatables.min.js"></script>-->
        <script type="text/javascript" src="{% static 'dynamic_schemas/dependencies/dt/datatables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'dynamic_schemas/js/main.js' %}"></script>
{% endblock %}

{% block navextras %}

    {% if schema.has_ancestor %}
    {# This might have to be a dropdownlist #}
    {% for s in schema_obsolete %}
    <li class="obs-schema">
        <a href="{% url 'dynamic_schemas:schema_view' s.obsolete_schema.id %}">
            <span class='glyphicon glyphicon-warning-sign'></span>
            Udgået skema: {{ s.obsolete_schema }}
        </a>
    </li>
    {% endfor %}
    {% endif %}
{% endblock %}

{% block content %}
{% load tz %}
{% localtime on %}
{% if schema.is_obsolete %}
<pre class="bg-danger"> 
    <h3>
        Denne tabel er udgået dato: {{ schema.date_obsolete }}, 
        gå tilbage til menuen for at finde din tabel.
        Hvis den ikke er herunder eller i menuen, kontakt admin!
        {% for s in schema_new %}
        <a href="{% url 'dynamic_schemas:schema_view' s.new_schema.id %}">{{ s.new_schema }}</a>
        {% endfor %}
    </h3>
</pre>
{% endif %}
{% endlocaltime %}

{% if all_responses %}
    <div class="dataTables-container">
        <table id="dataTable" class="display table table-striped" cellspacing="0" width="100%">
            <thead>
                <tr>
                    {% for h, r in single_response.items %}
                        {% if h == 'id' %}
                        <th>
                            ID
                        </th>
                        {% endif %}
                        {% if h == 'pub_date' %}
                        <th>
                            Dato
                        </th>
                        {% endif %}
                        {% if h == 'user' %}
                        <th>
                            Lavet af	
                        </th>
                        {% endif %}
                        {% if h == 'qa_set' %}
                            {% for key, value in r|load_json %}
                            <th>
                            {{ key }}
                            </th>
                            {% endfor %}
                        {% endif %}
                        {% if h == 'instruction' %}
                            <th>
                                Intruks
                            </th>
                        {% endif %}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in all_responses %}
                <tr>
                {% for h, r in row.items %}
                    {% if h == 'qa_set' %}
                        {% for key, value in r|load_json %}
                        <td>
                            {{ value }}
                        </td>
                        {% endfor %}
                    {% elif h == 'user' %}
                        <td>
                            {{ r|get_full_user_name }}
                        </td>
                    {% elif h == 'instruction' %}
                        <td>
                            <a href="{{ r|get_link }}" target="_blank">
                                {{ r|get_link_name }}
                            </a>
                        </td>

                    {% elif h != 'schema' %}
                        <td>
                            {{ r }}
                        </td>

                    {% endif %}
                {% endfor %}
                </tr> 
                {% endfor %}
        </table>
    </div>
    {% else %}
    <h1> SKEMA ER TOMT! Tryk under for at lave første indtasting! </h1>
     <a class="btn btn-primary" href="{% url 'dynamic_schemas:create_form' pk=pk %}">Ny Indtastning</a>
    {% endif %}
{% endblock %}

dynamic_schemas/templates/dynamic_schemas/table_dev.html
{% extends 'dynamic_schemas/base.html' %}
{% load static %}
{% load dynamic_schema_extras %}
{% block extraheads %}
        <link rel="stylesheet" type="text/css" href="{% static 'dynamic_schemas/dependencies/dt/datatables.min.css' %}">

        <script type="text/javascript" 
                src="{% static 'dynamic_schemas/dependencies/dt/datatables.js' %}"></script>
        <script type="text/javascript" 
                src="{% static 'dynamic_schemas/js/table_dev.js' %}"></script>
{% endblock %}

{% block navextras %}

    {% if schema.has_ancestor %}
    {# This might have to be a dropdownlist #}
    {% for s in schema_obsolete %}
    <li class="obs-schema">
        <a href="{% url 'dynamic_schemas:schema_view' s.obsolete_schema.id %}">
            <span class='glyphicon glyphicon-warning-sign'></span>
            Udgået skema: {{ s.obsolete_schema }}
        </a>
    </li>
    {% endfor %}
    {% endif %}
{% endblock %}

{% block content %}
{% load tz %}
{% localtime on %}
{% if schema.is_obsolete %}
<pre class="bg-danger"> 
    <h3>
        Denne tabel er udgået dato: {{ schema.date_obsolete }}, 
        gå tilbage til menuen for at finde din tabel.
        Hvis den ikke er herunder eller i menuen, kontakt admin!
        {% for s in schema_new %}
        <a href="{% url 'dynamic_schemas:schema_view' s.new_schema.id %}">{{ s.new_schema }}</a>
        {% endfor %}
    </h3>
</pre>
{% endif %}
{% endlocaltime %}

{% if all_responses %}
    <div class="dataTables-container">
        <table id="dataTable" class="display table table-striped" width="100%">
        </table>
    </div>
{% else %}
    <h1> SKEMA ER TOMT! Tryk under for at lave første indtasting! </h1>
     <a class="btn btn-primary" href="{% url 'dynamic_schemas:create_form' pk=pk %}">Ny Indtastning</a>
{% endif %}
{% endblock %}

dynamic_schemas/templates/dynamic_schemas/update-form.html
{% extends 'dynamic_schemas/base.html' %}
{% load dynamic_schema_extras %}

{% block content %}
    <div class="form-container">
        <form class="form-box" action="" method="POST" >
            <!--<input type="hidden" name="_method" value="PUT"/>-->
            {% csrf_token %}
            {% if form_update %}
                {% for field in form_update %} 
                    {% if field.is_hidden %} 
                        {{ field }}
                    {% elif field|is_a_checkbox %}
                    <div class="form-check">
                        <label class="form-check-label" for="id_{{ field.label }}"> 
                            {{ field }}
                            {{ field.label }}
                        </label>
                    </div>
                    {% else %}
                        {{ field.label_tag }}
                        {{ field }}
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if load_button %}
                <input type="submit" value="GEM" class="btn btn-default pull-right submit-btn"/>
            {% endif %}
        </form>
    </div>
{% endblock %}